### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by Jotalz** [SunOner/mouse_net#1]
Hello,I tried training using your model.
After one pass, it outputs this:
 ![train](https://github.com/SunOner/mouse_net/assets/57427866/0e517c46-dcf4-41e7-adb9-06cfb9b7cf7d)
![Figure_1](https://github.com/SunOner/mouse_net/assets/57427866/69a270ac-7351-472d-99a2-61adb4cda2df)

and the test output without data change:
```
Starting testing model...
Mean Squared Error on Test Data: 70.91168212890625
```

Is this a sign that it's working properly? Should I increase the amount of train data?

**Comment by SunOner** [comment]
https://github.com/SunOner/mouse_net/commit/176de530502cf8ce0438cb7d8bf66d99d4f6ca3c

**Comment by Jotalz** [comment]
> [176de53](https://github.com/SunOner/mouse_net/commit/176de530502cf8ce0438cb7d8bf66d99d4f6ca3c)
I tried training using the parameters you suggested,It took a long time and I don't think it was using my GPU
![Figure_1](https://github.com/SunOner/mouse_net/assets/57427866/916b1aa3-a1a0-46cf-91db-6185dda8a88e)
![{51C7F173-3571-4e2a-895B-EEBD5B05927B}](https://github.com/SunOner/mouse_net/assets/57427866/70b782b5-312c-47f4-a31b-32b0361fbf2d)
![{C51A7CB4-928C-4356-9DF6-A83A24CA3B99}](https://github.com/SunOner/mouse_net/assets/57427866/9f699ad5-354c-44a0-982d-b4a6b99a1a6d)
My CPU is occupied 60%+ for a long time,but the gpu is always at 10%+ or 20%
